version: '3.8'

services:
  libraryapp:
    image: libraryapp
    build:
      context: .
      dockerfile: LibraryApp/Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - postgresdb
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgresdb;Database=cinema_db;Username=user;Password=password

  postgresdb:
    image: postgres:latest
    environment:
      POSTGRES_DB: cinema_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
