# This is a generated file. Not intended for manual editing.
version: "3.8"
services:
  libraryapp:
    build:
      context: "D:\\Programmiring\\LibraryApp"
      dockerfile: "LibraryApp/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/LibraryApp.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_STATICWEBASSETS: "/app/bin/Debug/net8.0/LibraryApp.staticwebassets.runtime.CT.json"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "libraryapp:dev"
    ports: []
    volumes:
    - "C:\\Users\\nik06\\.nuget\\packages:/home/app/.nuget/packages"
    - "D:\\Programmiring\\LibraryApp\\LibraryApp:/app:rw"
    - "D:\\Programmiring\\LibraryApp:/src:rw"
    working_dir: "/app"
